"""Add marks and other columns to question tables

Revision ID: 90a7d4d612c7
Revises: df9f428322d5
Create Date: 2025-07-25 08:12:37.083948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a7d4d612c7'
down_revision = 'df9f428322d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('starter_code_python', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('starter_code_java', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('starter_code_cpp', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('starter_code_c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('starter_code_javascript', sa.Text(), nullable=True))
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mcq_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('correct_option_id', sa.Integer(), nullable=True))
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_correct_option_id', 'mcq_option', ['correct_option_id'], ['id'], use_alter=True)
        batch_op.drop_column('option_c')
        batch_op.drop_column('correct_option')
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_b')
        batch_op.drop_column('option_a')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.alter_column('expected_output',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('expected_output',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('mcq_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_a', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('option_b', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('option_d', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correct_option', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('option_c', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_correct_option_id', type_='foreignkey')
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('correct_option_id')
        batch_op.drop_column('marks')

    with op.batch_alter_table('coding_question', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('starter_code_javascript')
        batch_op.drop_column('starter_code_c')
        batch_op.drop_column('starter_code_cpp')
        batch_op.drop_column('starter_code_java')
        batch_op.drop_column('starter_code_python')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
